name: BedWars
version: 0.50
api: [3.0.0, 4.0.0]
main: Epic\Bedwars
author: bittch
commands:
    bw:
        description: BedWars Main Command
        aliases: [bw]
    start:
        description: BedWars Forcestart Command
