name: BedWars
version: 0.1
api: 3.0.0
main: Epic\Bedwars
author: bittch
website: http://www.kcmcpe.net
commands:
    bedwars:
        description: BedWars Main Command
        aliases: [bw]
    start:
        description: Bedwars Forcestart Command
